import { InventoryData, LineItemsData, OpportunityData } from "./models";

export const sampleOpportunities: Array<OpportunityData> = [
    {
        "Id": "006Mm00000ByeqgIAC",
        "DealValue": 31775000.0,
        "AutomaticAmount": 31775000.0,
        "ManualAmount": 500000.0,
        "CashAmount": 0,
        "TargetAmount": 0,
        "PricingMode": "Automatic",
        "TotalHardCost": 35000.0,
        "TotalProductionCost": 35000.0,
        "TotalRateCard": 35000.0,
        "PercentOfRate": 0.87,
        "PercentOfRateCard": 87,
        "EscalationType": null,
        "EscalationValue": null,
        "SeasonName": "2024",
        "StartSeason": "006Mm00000ByeqgIAC"
    },
    {
        "Id": "006Mm00000ByeqgIAD",
        "DealValue": 6700000.0,
        "AutomaticAmount": 36875000.0,
        "ManualAmount": 6700000.0,
        "CashAmount": 0,
        "TargetAmount": 0,
        "PricingMode": "Manual",
        "TotalHardCost": 36050.0,
        "TotalProductionCost": 36050.0,
        "TotalRateCard": 36050.0,
        "PercentOfRate": 0.87,
        "PercentOfRateCard": 87,
        "EscalationType": "Percent",
        "EscalationValue": 0.02,
        "SeasonName": "2025",
        "StartSeason": "006Mm00000ByeqgIAD"
    },
    {
        "Id": "006Mm00000ByeqgIAE",
        "DealValue": 360785000.0,
        "AutomaticAmount": 360785000.0,
        "ManualAmount": 0,
        "CashAmount": 0,
        "TargetAmount": 0,
        "PricingMode": "Automatic",
        "TotalHardCost": 37120.0,
        "TotalProductionCost": 37120.0,
        "TotalRateCard": 37120.0,
        "PercentOfRate": 0.87,
        "PercentOfRateCard": 87,
        "EscalationType": null,
        "EscalationValue": null,
        "SeasonName": "2026",
        "StartSeason": "006Mm00000ByeqgIAE"
    },
    {
        "Id": "006Mm00000ByeqgIAF",
        "DealValue": 36875000.0,
        "AutomaticAmount": 36875000.0,
        "ManualAmount": 6980000.0,
        "CashAmount": 0,
        "TargetAmount": 0,
        "PricingMode": "Automatic",
        "TotalHardCost": 38204.4,
        "TotalProductionCost": 38204.4,
        "TotalRateCard": 38204.4,
        "PercentOfRate": 0.87,
        "PercentOfRateCard": 87,
        "EscalationType": null,
        "EscalationValue": null,
        "SeasonName": "2027",
        "StartSeason": "006Mm00000ByeqgIAF"
    }
]

export const sampleLineItems: LineItemsData = [
    {
        "Product2": {
            "Id": "006Mm00000ByeqgIAZ",
            "Name": "Back Panel Advertisement (per 5,000 units) VALUE ADD",
            "Division": "Division 1",
            "ProductFamily": "Print",
            "ProductSubFamily": "Pocket Schedules",
            "IsPassthroughCost": false,
            "IsPackage": false
        },
        "rates": [
            {
                "RateType": "Individual",
                "Rate": 2000000.0,
                "HardCost": 100000.0,
                "ProductionCost": 50000.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAC",
                "SeasonName": "2024",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAZ"
            },
            {
                "RateType": "Individual",
                "Rate": 2040000.0,
                "HardCost": 102000.0,
                "ProductionCost": 51000.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAD",
                "SeasonName": "2025",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAZ"
            },
            {
                "RateType": "Individual",
                "Rate": 2080800.0,
                "HardCost": 104040.0,
                "ProductionCost": 52020.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAE",
                "SeasonName": "2026",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAZ"
            },
            {
                "RateType": "Individual",
                "Rate": 2122416.0,
                "HardCost": 106120.8,
                "ProductionCost": 53060.4,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAF",
                "SeasonName": "2027",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAZ"
            }
        ],
        "items": [
            {
                "Id": "006Mm00000ByeqgITY", // OpportunityProductId
                "Opportunity": "006Mm00000ByeqgIAC",
                "TotalValue": 2000000.0,
                "QtyEvents": 5,
                "QtyUnits": 100000,
                "HardCost": 100000.0,
                "TotalHardCost": 100000.0,
                "ProductionCost": 50000.0,
                "TotalProductionCost": 50000.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAZ",
                "Rate": 2000000.0,
                "QuantityAvailable": 500,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": false,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqgIOP",
                "Opportunity": "006Mm00000ByeqgIAD",
                "TotalValue": 2040000.0,
                "QtyEvents": 5,
                "QtyUnits": 0,
                "HardCost": 102000.0,
                "TotalHardCost": 102000.0,
                "ProductionCost": 51000.0,
                "TotalProductionCost": 51000.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAZ",
                "Rate": 2040000.0,
                "QuantityAvailable": 490,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": false,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "<p>Hello World legal definition override at oli level </p>",
                "OverwriteLegalDefinition": true,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqgINB",
                "Opportunity": "006Mm00000ByeqgIAE",
                "TotalValue": 2080800.0,
                "QtyEvents": 5,
                "QtyUnits": 10,
                "HardCost": 104040.0,
                "TotalHardCost": 104040.0,
                "ProductionCost": 52020.0,
                "TotalProductionCost": 52020.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAZ",
                "Rate": 2080800.0,
                "QuantityAvailable": 480,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqgILK",
                "Opportunity": "006Mm00000ByeqgIAF",
                "TotalValue": 2122416.0,
                "QtyEvents": 5,
                "QtyUnits": 10,
                "HardCost": 106120.8,
                "TotalHardCost": 106120.8,
                "ProductionCost": 53060.4,
                "TotalProductionCost": 53060.4,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAZ",
                "Rate": 2122416.0,
                "QuantityAvailable": 470,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            }
        ],
        "IsPackage": false,
        "IsPackageComponent": false,
        "PackageComponents": []
    },
    {
        "Product2": {
            "Id": "006Mm00000ByeqgIAY",
            "Name": "Social Media Mentions",
            "Division": "Division 2",
            "ProductFamily": "Digital",
            "ProductSubFamily": "Social Media",
            "IsPassthroughCost": false,
            "IsPackage": true
        },
        "rates": [
            {
                "RateType": "Individual",
                "Rate": 1500000.0,
                "HardCost": 75000.0,
                "ProductionCost": 37500.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAC",
                "SeasonName": "2024",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAY"
            },
            {
                "RateType": "Individual",
                "Rate": 1530000.0,
                "HardCost": 76500.0,
                "ProductionCost": 38250.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAD",
                "SeasonName": "2025",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAY"
            },
            {
                "RateType": "Individual",
                "Rate": 1560600.0,
                "HardCost": 78030.0,
                "ProductionCost": 39015.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAE",
                "SeasonName": "2026",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAY"
            },
            {
                "RateType": "Individual",
                "Rate": 1591812.0,
                "HardCost": 79590.6,
                "ProductionCost": 39795.3,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAF",
                "SeasonName": "2027",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIAY"
            }
        ],
        "items": [
            {
                "Id": "006Mm00000ByeqgILJ",
                "Opportunity": "006Mm00000ByeqgIAC",
                "TotalValue": 1500000.0,
                "QtyEvents": 4,
                "QtyUnits": 8,
                "HardCost": 75000.0,
                "TotalHardCost": 75000.0,
                "ProductionCost": 37500.0,
                "TotalProductionCost": 37500.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAY",
                "Rate": 1500000.0,
                "QuantityAvailable": 300,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqgIASD",
                "Opportunity": "006Mm00000ByeqgIAD",
                "TotalValue": 1530000.0,
                "QtyEvents": 4,
                "QtyUnits": 8,
                "HardCost": 76500.0,
                "TotalHardCost": 76500.0,
                "ProductionCost": 38250.0,
                "TotalProductionCost": 38250.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAY",
                "Rate": 1530000.0,
                "QuantityAvailable": 290,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": true,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "<p>Hello World legal definition override at oli level </p>",
                "OverwriteLegalDefinition": true,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqAJKQA",
                "Opportunity": "006Mm00000ByeqgIAE",
                "TotalValue": 1560600.0,
                "QtyEvents": 4,
                "QtyUnits": 0,
                "HardCost": 78030.0,
                "TotalHardCost": 78030.0,
                "ProductionCost": 39015.0,
                "TotalProductionCost": 39015.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAY",
                "Rate": 1560600.0,
                "QuantityAvailable": 280,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqAJSN",
                "Opportunity": "006Mm00000ByeqgIAF",
                "TotalValue": 1591812.0,
                "QtyEvents": 4,
                "QtyUnits": 8,
                "HardCost": 79590.6,
                "TotalHardCost": 79590.6,
                "ProductionCost": 39795.3,
                "TotalProductionCost": 39795.3,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIAY",
                "Rate": 1591812.0,
                "QuantityAvailable": 270,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            }
        ],
        "IsPackage": false,
        "IsPackageComponent": false,
        "PackageComponents": []
    },
    {
        "Product2": {
            "Id": "006Mm00000ByeqgIBX",
            "Name": "Field Goal Mentions",
            "Division": "Division 1",
            "ProductFamily": "Digital",
            "ProductSubFamily": "Event Mentions",
            "IsPassthroughCost": true,
            "IsPackage": false
        },
        "rates": [
            {
                "RateType": "Individual",
                "Rate": 1800000.0,
                "HardCost": 90000.0,
                "ProductionCost": 45000.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAC",
                "SeasonName": "2024",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIBX"
            },
            {
                "RateType": "Individual",
                "Rate": 1836000.0,
                "HardCost": 91800.0,
                "ProductionCost": 45900.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAD",
                "SeasonName": "2025",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIBX"
            },
            {
                "RateType": "Individual",
                "Rate": 1872720.0,
                "HardCost": 93636.0,
                "ProductionCost": 46818.0,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAE",
                "SeasonName": "2026",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIBX"
            },
            {
                "RateType": "Individual",
                "Rate": 1910174.4,
                "HardCost": 95508.72,
                "ProductionCost": 47754.36,
                "LockHardCost": true,
                "LockRate": true,
                "LockProductionCost": true,
                "Season": "006Mm00000ByeqgIAF",
                "SeasonName": "2027",
                "UnlimitedQuantity": false,
                "Product": "006Mm00000ByeqgIBX"
            }
        ],
        "items": [
            {
                "Id": "006Mm00000ByeqQAD",
                "Opportunity": "006Mm00000ByeqgIAC",
                "TotalValue": 1800000.0,
                "QtyEvents": 6,
                "QtyUnits": 12,
                "HardCost": 90000.0,
                "TotalHardCost": 90000.0,
                "ProductionCost": 45000.0,
                "TotalProductionCost": 45000.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIBX",
                "Rate": 1800000.0,
                "QuantityAvailable": 400,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqOuY",
                "Opportunity": "006Mm00000ByeqgIAD",
                "TotalValue": 1836000.0,
                "QtyEvents": 6,
                "QtyUnits": 12,
                "HardCost": 91800.0,
                "TotalHardCost": 91800.0,
                "ProductionCost": 45900.0,
                "TotalProductionCost": 45900.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIBX",
                "Rate": 1836000.0,
                "QuantityAvailable": 390,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "Test description",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqAZCN",
                "Opportunity": "006Mm00000ByeqgIAE",
                "TotalValue": 1872720.0,
                "QtyEvents": 6,
                "QtyUnits": 12,
                "HardCost": 93636.0,
                "TotalHardCost": 93636.0,
                "ProductionCost": 46818.0,
                "TotalProductionCost": 46818.0,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIBX",
                "Rate": 1872720.0,
                "QuantityAvailable": 380,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "<p>Hello World legal definition override at oli level </p>",
                "OverwriteLegalDefinition": true,
                "Description": "",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": false,
                "PackageLineItemId": null
            },
            {
                "Id": "006Mm00000ByeqAMNA",
                "Opportunity": "006Mm00000ByeqgIAF",
                "TotalValue": 1910174.4,
                "QtyEvents": 6,
                "QtyUnits": 0,
                "HardCost": 95508.72,
                "TotalHardCost": 95508.72,
                "ProductionCost": 47754.36,
                "TotalProductionCost": 47754.36,
                "LockProductionCost": true,
                "Product2": "006Mm00000ByeqgIBX",
                "Rate": 1910174.4,
                "QuantityAvailable": 370,
                "RateType": "Individual",
                "IsActive": true,
                "LockHardCost": true,
                "LockRate": true,
                "IsManualPriceOverride": false,
                "ResetOverride": false,
                "LegalDefinitionProduct": "<p>Hello LegalDefinitionProduct</p>",
                "LegalDefinitionInventoryBySeason": "<p>Hello LegalDefinitionInventoryBySeason</p>",
                "LegalDefinition": "",
                "OverwriteLegalDefinition": false,
                "Description": "",
                "QuantityTotal": 10,
                "QuantitySold": 2,
                "QuantityPitched": 1,
                "NotAvailable": true,
                "PackageLineItemId": null
            }
        ],
        "IsPackage": false,
        "IsPackageComponent": false,
        "PackageComponents": []
    }

]

export const sampleInventory: Array<InventoryData> = [
    {
        "ProductId": "001Mm0000001qRAZ",
        "ProductName": "Stadium Banner Ads",
        "ProductFamily": "Advertising",
        "ProductSubFamily": "Banners",
        "Division": "Division A",
        "IsPassthroughCost": false,
        "RateType": "Individual",
        "Rate": 2000.0,
        "RateId": "R001Mm00000001qRAZ",
        "LockRate": true,
        "HardCost": 1000.0,
        "LockHardCost": true,
        "ProductionCost": 500.0,
        "LockProductionCost": true,
        "QuantityAvailable": 100,
        "QtyUnits": 10,
        "QtyEvents": 2,
        "IsPackage": false,
        "Description": "High visibility banner ads around the stadium.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRBZ",
        "ProductName": "Field Goal Sponsorship",
        "ProductFamily": "Sponsorship",
        "ProductSubFamily": "Events",
        "Division": "Division B",
        "IsPassthroughCost": false,
        "RateType": "Season",
        "Rate": 5000.0,
        "RateId": "R001Mm00000001qRBZ",
        "LockRate": false,
        "HardCost": 2500.0,
        "LockHardCost": true,
        "ProductionCost": 1000.0,
        "LockProductionCost": false,
        "QuantityAvailable": 200,
        "QtyUnits": 15,
        "QtyEvents": 3,
        "IsPackage": false,
        "Description": "Exclusive sponsorship of field goal attempts during the season.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRCZ",
        "ProductName": "Digital Mentions",
        "ProductFamily": "Digital",
        "ProductSubFamily": "Social Media",
        "Division": "Division C",
        "IsPassthroughCost": false,
        "RateType": "Individual",
        "Rate": 1500.0,
        "RateId": "R001Mm00000001qRCZ",
        "LockRate": true,
        "HardCost": 700.0,
        "LockHardCost": false,
        "ProductionCost": 300.0,
        "LockProductionCost": true,
        "QuantityAvailable": 150,
        "QtyUnits": 20,
        "QtyEvents": 5,
        "IsPackage": false,
        "Description": "Social media mentions during Individual days.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRDZ",
        "ProductName": "Scoreboard Ads",
        "ProductFamily": "Advertising",
        "ProductSubFamily": "Displays",
        "Division": "Division D",
        "IsPassthroughCost": true,
        "RateType": "Season",
        "Rate": 10000.0,
        "RateId": "R001Mm00000001qRDZ",
        "LockRate": true,
        "HardCost": 5000.0,
        "LockHardCost": true,
        "ProductionCost": 2000.0,
        "LockProductionCost": false,
        "QuantityAvailable": 50,
        "QtyUnits": 8,
        "QtyEvents": 1,
        "IsPackage": false,
        "Description": "Advertisement slots on the stadium scoreboard for the entire season.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qREZ",
        "ProductName": "Promotional Flyers",
        "ProductFamily": "Print",
        "ProductSubFamily": "Promotions",
        "Division": "Division E",
        "IsPassthroughCost": false,
        "RateType": "Individual",
        "Rate": 1000.0,
        "RateId": "R001Mm00000001qREZ",
        "LockRate": false,
        "HardCost": 500.0,
        "LockHardCost": false,
        "ProductionCost": 200.0,
        "LockProductionCost": true,
        "QuantityAvailable": 300,
        "QtyUnits": 50,
        "QtyEvents": 10,
        "IsPackage": false,
        "Description": "Flyers distributed during games for promotions.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRFZ",
        "ProductName": "Halftime Sponsorship",
        "ProductFamily": "Sponsorship",
        "ProductSubFamily": "Events",
        "Division": "Division F",
        "IsPassthroughCost": false,
        "RateType": "Season",
        "Rate": 15000.0,
        "RateId": "R001Mm00000001qRFZ",
        "LockRate": true,
        "HardCost": 7500.0,
        "LockHardCost": true,
        "ProductionCost": 2500.0,
        "LockProductionCost": true,
        "QuantityAvailable": 10,
        "QtyUnits": 1,
        "QtyEvents": 1,
        "IsPackage": false,
        "Description": "Exclusive sponsorship of halftime shows for the season.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRGZ",
        "ProductName": "VIP Lounge Branding",
        "ProductFamily": "Branding",
        "ProductSubFamily": "On-Site",
        "Division": "Division G",
        "IsPassthroughCost": true,
        "RateType": "Individual",
        "Rate": 5000.0,
        "RateId": "R001Mm00000001qRGZ",
        "LockRate": true,
        "HardCost": 2500.0,
        "LockHardCost": false,
        "ProductionCost": 1000.0,
        "LockProductionCost": false,
        "QuantityAvailable": 5,
        "QtyUnits": 2,
        "QtyEvents": 1,
        "IsPackage": false,
        "Description": "Branding opportunities in the VIP lounge during games.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRHZ",
        "ProductName": "Mascot Sponsorship",
        "ProductFamily": "Sponsorship",
        "ProductSubFamily": "Branding",
        "Division": "Division H",
        "IsPassthroughCost": false,
        "RateType": "Season",
        "Rate": 3000.0,
        "RateId": "R001Mm00000001qRHZ",
        "LockRate": false,
        "HardCost": 1500.0,
        "LockHardCost": true,
        "ProductionCost": 700.0,
        "LockProductionCost": true,
        "QuantityAvailable": 25,
        "QtyUnits": 10,
        "QtyEvents": 2,
        "IsPackage": false,
        "Description": "Sponsorship opportunities with the team mascot for the season.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRIZ",
        "ProductName": "Social Media Posts",
        "ProductFamily": "Digital",
        "ProductSubFamily": "Social Media",
        "Division": "Division I",
        "IsPassthroughCost": true,
        "RateType": "Individual",
        "Rate": 1200.0,
        "RateId": "R001Mm00000001qRIZ",
        "LockRate": true,
        "HardCost": 500.0,
        "LockHardCost": true,
        "ProductionCost": 300.0,
        "LockProductionCost": false,
        "QuantityAvailable": 400,
        "QtyUnits": 25,
        "QtyEvents": 4,
        "IsPackage": false,
        "Description": "Social media posts promoting the team during Individual days.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRJZ",
        "ProductName": "Pre-Individual Sponsorship",
        "ProductFamily": "Sponsorship",
        "ProductSubFamily": "Events",
        "Division": "Division J",
        "IsPassthroughCost": false,
        "RateType": "Season",
        "Rate": 10000.0,
        "RateId": "R001Mm00000001qRJZ",
        "LockRate": true,
        "HardCost": 4500.0,
        "LockHardCost": true,
        "ProductionCost": 2000.0,
        "LockProductionCost": true,
        "QuantityAvailable": 15,
        "QtyUnits": 12,
        "QtyEvents": 3,
        "IsPackage": false,
        "Description": "Sponsorship opportunities before each Individual for the season.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRKZ",
        "ProductName": "Player Appearance Branding",
        "ProductFamily": "Branding",
        "ProductSubFamily": "Player Appearances",
        "Division": "Division K",
        "IsPassthroughCost": true,
        "RateType": "Individual",
        "Rate": 8000.0,
        "RateId": "R001Mm00000001qRKZ",
        "LockRate": false,
        "HardCost": 3000.0,
        "LockHardCost": true,
        "ProductionCost": 1500.0,
        "LockProductionCost": true,
        "QuantityAvailable": 10,
        "QtyUnits": 3,
        "QtyEvents": 1,
        "IsPackage": false,
        "Description": "Branding opportunities during player appearances at games.",
        "PackageComponents": []
    },
    {
        "ProductId": "001Mm0000001qRLZ",
        "ProductName": "Email Campaign Mentions",
        "ProductFamily": "Digital",
        "ProductSubFamily": "Email Campaigns",
        "Division": "Division L",
        "IsPassthroughCost": false,
        "RateType": "Season",
        "Rate": 5000.0,
        "RateId": "R001Mm00000001qRLZ",
        "LockRate": true,
        "HardCost": 2500.0,
        "LockHardCost": true,
        "ProductionCost": 1000.0,
        "LockProductionCost": true,
        "QuantityAvailable": 120,
        "QtyUnits": 10,
        "QtyEvents": 2,
        "IsPackage": false,
        "Description": "Mentions in email campaigns throughout the season.",
        "PackageComponents": []
    },
];
