using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using MultiYearDeal.Workflows;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;

namespace MultiYearDeal.Plugins
{
    // -------------------------------------------------------------------------
    // ats_CheckProductsAvailability — pre-flight for the Agreement Cart
    // "Add Products (batch)" flow.
    // -------------------------------------------------------------------------
    //
    // V2 (17-Apr-2026) changes vs. the MVP:
    //   1. IBS auto-generation: when an IBS is missing for a (product, season)
    //      pair, the plugin tries to find ANY existing IBS for that product
    //      (across any season), uses it as a template, and clones it into
    //      the target season (same fields the legacy EnsureInventoryForSeasonOptimized
    //      copies: description, allowoverselling, unlimitedquantity,
    //      totalquantity, totalquantityperevent, eventschedule reference).
    //      The new IBS is marked `ats_autogenerated = true`.
    //   2. Rate auto-generation: when the IBS exists (or was just created)
    //      but the requested rate type is missing, the plugin creates a rate
    //      on that IBS using the Rate / HardCost / ProductionCost values
    //      supplied in the request. Also flagged `ats_autogenerated = true`.
    //   3. "use_legacy_flow" verdict is gone. Package products (IsPackage /
    //      packageLineId) are validated like any other product here. The
    //      batch creation of package components is handled by
    //      CustomAPIAddProductsBatch.
    //   4. Response casing normalised to lowercase camelCase throughout so the
    //      PCF consumer stays stable regardless of DTO tweaks.
    //
    // Contract:
    //   Input parameters (strings):
    //     agreementId : GUID of the ats_agreement record.
    //     products    : JSON array of ProductRequest (see bottom of file).
    //
    //   Output parameter:
    //     response    : JSON string:
    //       {
    //         allOk: bool,
    //         generatedAt: ISO-8601 UTC string,
    //         results: [
    //           { productId, seasonId,
    //             verdict: "ok" | "ibs_missing" | "rate_missing" | "oversell_blocked",
    //             ibsExists, rateExists,
    //             qtyAvailable, allowOverselling, unlimitedQuantity,
    //             ibsId?, rateId?,
    //             ibsAutoCreated?, rateAutoCreated? }
    //         ]
    //       }
    //
    // Non-breaking for the PCF: the payload field names are unchanged from
    // V1; the only additions are the two booleans at the end that the PCF
    // can ignore or use for UI feedback.
    // -------------------------------------------------------------------------
    public class CustomAPICheckProductsAvailability : IPlugin
    {
        private const int RateTypeSeason = 114300000;
        private const int RateTypeIndividual = 114300001;

        public void Execute(IServiceProvider serviceProvider)
        {
            var tracingService = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            var pluginContext = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
            var serviceFactory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
            var service = serviceFactory.CreateOrganizationService(pluginContext.UserId);

            try
            {
                TraceHelper.Initialize(service);
                TraceHelper.Trace(tracingService, "CheckProductsAvailability v2: begin");

                string agreementIdStr = GetInputString(pluginContext, "agreementId");
                string productsJson = GetInputString(pluginContext, "products");

                if (string.IsNullOrWhiteSpace(agreementIdStr) || string.IsNullOrWhiteSpace(productsJson))
                    throw new InvalidPluginExecutionException(
                        "CheckProductsAvailability requires non-empty 'agreementId' and 'products' input parameters.");

                if (!Guid.TryParse(agreementIdStr, out _))
                    throw new InvalidPluginExecutionException(
                        "CheckProductsAvailability: 'agreementId' is not a valid GUID.");

                List<ProductRequest> requests;
                try
                {
                    requests = JsonSerializer.Deserialize<List<ProductRequest>>(productsJson)
                               ?? new List<ProductRequest>();
                }
                catch (Exception ex)
                {
                    throw new InvalidPluginExecutionException(
                        "CheckProductsAvailability: failed to deserialize 'products' JSON.", ex);
                }

                if (requests.Count == 0)
                {
                    SetResponse(pluginContext, new AvailabilityResult
                    {
                        allOk = true,
                        generatedAt = DateTime.UtcNow.ToString("o"),
                        results = new List<PairVerdict>()
                    });
                    return;
                }

                // Flatten to (product, season) pairs (plus the request that generated
                // each pair so we can reach back for Rate / HardCost / ProductionCost
                // during auto-creation).
                var pairs = new List<RequestedPair>();
                var productIdSet = new HashSet<Guid>();
                var seasonIdSet = new HashSet<Guid>();

                foreach (var req in requests)
                {
                    if (req == null || !Guid.TryParse(req.ProductId, out var productGuid)) continue;

                    var seasonGuids = ParseSeasonIds(req.seasonIds);
                    if (seasonGuids.Count == 0)
                    {
                        pairs.Add(new RequestedPair
                        {
                            ProductId = productGuid,
                            SeasonId = Guid.Empty,
                            Req = req
                        });
                        productIdSet.Add(productGuid);
                        continue;
                    }

                    foreach (var seasonGuid in seasonGuids)
                    {
                        pairs.Add(new RequestedPair
                        {
                            ProductId = productGuid,
                            SeasonId = seasonGuid,
                            Req = req
                        });
                        productIdSet.Add(productGuid);
                        seasonIdSet.Add(seasonGuid);
                    }
                }

                // 1. Resolve existing IBS + Rate for the whole request in one fetch.
                var resolution = ResolveInBulk(service, productIdSet, seasonIdSet, tracingService);

                // 2. For every pair whose IBS is missing, try to auto-create it.
                //    Templates are searched per-product on first miss and cached.
                var templateCache = new Dictionary<Guid, Entity>(); // productId -> template IBS
                foreach (var pair in pairs)
                {
                    if (pair.SeasonId == Guid.Empty) continue;
                    var key = MakePairKey(pair.ProductId, pair.SeasonId);
                    if (resolution.Ibs.ContainsKey(key)) continue;

                    var created = TryAutoCreateIbs(service, pair.ProductId, pair.SeasonId, templateCache, tracingService);
                    if (created != null)
                    {
                        resolution.Ibs[key] = created;
                        pair.IbsAutoCreated = true;
                    }
                }

                // 3. For every pair whose IBS now exists but rate is missing for the
                //    requested rate type, create the rate.
                foreach (var pair in pairs)
                {
                    if (pair.SeasonId == Guid.Empty) continue;
                    var key = MakePairKey(pair.ProductId, pair.SeasonId);
                    if (!resolution.Ibs.TryGetValue(key, out var ibs)) continue;

                    int rateType = NormalizeRateType(pair.Req.RateType);
                    if (ibs.RatesByType.TryGetValue(rateType, out var existing) && !existing.Inactive) continue;

                    var createdRate = TryAutoCreateRate(service, ibs.IbsId, rateType, pair.Req, tracingService);
                    if (createdRate != null)
                    {
                        ibs.RatesByType[rateType] = createdRate;
                        pair.RateAutoCreated = true;
                    }
                }

                // 4. Evaluate every pair now that auto-creation has run.
                var results = new List<PairVerdict>(pairs.Count);
                bool allOk = true;

                foreach (var pair in pairs)
                {
                    var verdict = EvaluatePair(pair, resolution);
                    results.Add(verdict);
                    if (verdict.verdict != "ok") allOk = false;
                }

                SetResponse(pluginContext, new AvailabilityResult
                {
                    allOk = allOk,
                    generatedAt = DateTime.UtcNow.ToString("o"),
                    results = results
                });

                tracingService.Trace(
                    "CheckProductsAvailability v2: pairs={0} allOk={1}",
                    pairs.Count, allOk);
            }
            catch (InvalidPluginExecutionException)
            {
                throw;
            }
            catch (Exception ex)
            {
                tracingService.Trace("CheckProductsAvailability v2: unexpected exception: {0}", ex);
                throw new InvalidPluginExecutionException(
                    "CheckProductsAvailability failed.", ex);
            }
        }

        // --- Bulk resolution ------------------------------------------------

        private static BulkResolution ResolveInBulk(
            IOrganizationService service,
            HashSet<Guid> productIds,
            HashSet<Guid> seasonIds,
            ITracingService tracingService)
        {
            var resolution = new BulkResolution();
            if (productIds.Count == 0 || seasonIds.Count == 0) return resolution;

            var sb = new StringBuilder();
            sb.Append("<fetch no-lock='true'>");
            sb.Append("<entity name='ats_inventorybyseason'>");
            sb.Append("<attribute name='ats_inventorybyseasonid' />");
            sb.Append("<attribute name='ats_product' />");
            sb.Append("<attribute name='ats_season' />");
            sb.Append("<attribute name='ats_quantityavailable' />");
            sb.Append("<attribute name='ats_allowoverselling' />");
            sb.Append("<attribute name='ats_unlimitedquantity' />");
            sb.Append("<filter type='and'>");
            AppendInFilter(sb, "ats_product", productIds);
            AppendInFilter(sb, "ats_season", seasonIds);
            sb.Append("</filter>");
            sb.Append("<link-entity name='ats_rate' from='ats_inventorybyseason' to='ats_inventorybyseasonid' link-type='outer' alias='R'>");
            sb.Append("<attribute name='ats_rateid' />");
            sb.Append("<attribute name='ats_ratetype' />");
            sb.Append("<attribute name='ats_inactive' />");
            sb.Append("</link-entity>");
            sb.Append("<link-entity name='ats_eventschedule' from='ats_eventscheduleid' to='ats_eventschedule' link-type='outer' alias='ES'>");
            sb.Append("<attribute name='ats_expectedeventquantity' />");
            sb.Append("</link-entity>");
            sb.Append("</entity>");
            sb.Append("</fetch>");

            var ec = service.RetrieveMultiple(new FetchExpression(sb.ToString()));
            TraceHelper.Trace(tracingService, "Bulk resolution returned {0} row(s)", ec.Entities.Count);

            foreach (var row in ec.Entities)
            {
                var productRef = row.GetAttributeValue<EntityReference>("ats_product");
                var seasonRef = row.GetAttributeValue<EntityReference>("ats_season");
                if (productRef == null || seasonRef == null) continue;

                var key = MakePairKey(productRef.Id, seasonRef.Id);

                if (!resolution.Ibs.TryGetValue(key, out var info))
                {
                    info = new IbsInfo
                    {
                        IbsId = row.Id,
                        QuantityAvailable = row.Contains("ats_quantityavailable")
                            ? row.GetAttributeValue<int>("ats_quantityavailable") : 0,
                        AllowOverselling = row.GetAttributeValue<bool>("ats_allowoverselling"),
                        UnlimitedQuantity = row.GetAttributeValue<bool>("ats_unlimitedquantity"),
                        ExpectedEventQuantity = 0,
                        RatesByType = new Dictionary<int, RateInfo>()
                    };
                    resolution.Ibs[key] = info;
                }

                if (row.Contains("ES.ats_expectedeventquantity"))
                    info.ExpectedEventQuantity = Convert.ToInt32(
                        ((AliasedValue)row["ES.ats_expectedeventquantity"]).Value);

                if (row.Contains("R.ats_rateid") && row.Contains("R.ats_ratetype"))
                {
                    bool inactive = row.Contains("R.ats_inactive")
                        && (bool)((AliasedValue)row["R.ats_inactive"]).Value;

                    int rateType = ((OptionSetValue)((AliasedValue)row["R.ats_ratetype"]).Value).Value;
                    var rateId = (Guid)((AliasedValue)row["R.ats_rateid"]).Value;

                    info.RatesByType[rateType] = new RateInfo
                    {
                        RateId = rateId,
                        Inactive = inactive
                    };
                }
            }

            return resolution;
        }

        // --- IBS auto-creation ---------------------------------------------

        private static IbsInfo TryAutoCreateIbs(
            IOrganizationService service,
            Guid productId,
            Guid seasonId,
            Dictionary<Guid, Entity> templateCache,
            ITracingService tracingService)
        {
            // Find a template IBS for this product (any season).
            if (!templateCache.TryGetValue(productId, out var template))
            {
                var templateQuery = new QueryExpression("ats_inventorybyseason")
                {
                    ColumnSet = new ColumnSet(
                        "ats_inventorybyseasonid", "ats_name", "ats_description",
                        "ats_allowoverselling", "ats_unlimitedquantity",
                        "ats_recordtype", "ats_totalquantity", "ats_totalquantityperevent",
                        "ats_eventschedule", "ats_product"),
                    TopCount = 1,
                    NoLock = true,
                    Criteria =
                    {
                        Conditions =
                        {
                            new ConditionExpression("ats_product", ConditionOperator.Equal, productId),
                            new ConditionExpression("statecode", ConditionOperator.Equal, 0)
                        }
                    }
                };
                var ec = service.RetrieveMultiple(templateQuery);
                template = ec.Entities.Count > 0 ? ec.Entities[0] : null;
                templateCache[productId] = template; // cache null result too
            }

            if (template == null)
            {
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateIbs: no template IBS exists for product {0} — cannot auto-generate.",
                    productId);
                return null;
            }

            // Retrieve the target season's name to build the IBS name.
            string seasonName = "";
            try
            {
                var seasonRow = service.Retrieve("ats_season", seasonId, new ColumnSet("ats_name"));
                seasonName = seasonRow.GetAttributeValue<string>("ats_name") ?? "";
            }
            catch (Exception seasonEx)
            {
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateIbs: failed to retrieve season name for {0}: {1}",
                    seasonId, seasonEx.Message);
            }

            string baseName = template.GetAttributeValue<string>("ats_name") ?? "";
            string newName = string.IsNullOrWhiteSpace(seasonName)
                ? baseName
                : (baseName + " " + seasonName).Trim();

            var newIbs = new Entity("ats_inventorybyseason");
            newIbs["ats_product"] = new EntityReference("product", productId);
            newIbs["ats_season"] = new EntityReference("ats_season", seasonId);
            newIbs["ats_name"] = newName;
            newIbs["ats_autogenerated"] = true;

            CopyIfPresent(template, newIbs, "ats_description");
            CopyIfPresent(template, newIbs, "ats_allowoverselling");
            CopyIfPresent(template, newIbs, "ats_unlimitedquantity");
            CopyIfPresent(template, newIbs, "ats_recordtype");
            CopyIfPresent(template, newIbs, "ats_totalquantity");
            CopyIfPresent(template, newIbs, "ats_totalquantityperevent");
            // Event schedule copied by reference — a deeper clone requires a
            // season-specific schedule which is out of scope for the pre-flight.
            CopyIfPresent(template, newIbs, "ats_eventschedule");

            try
            {
                var newId = service.Create(newIbs);
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateIbs: created ibs {0} for product {1} season {2}",
                    newId, productId, seasonId);

                bool allowOverselling = template.Contains("ats_allowoverselling")
                    && template.GetAttributeValue<bool>("ats_allowoverselling");
                bool unlimited = template.Contains("ats_unlimitedquantity")
                    && template.GetAttributeValue<bool>("ats_unlimitedquantity");

                return new IbsInfo
                {
                    IbsId = newId,
                    QuantityAvailable = 0, // brand-new — no history
                    AllowOverselling = allowOverselling,
                    UnlimitedQuantity = unlimited,
                    ExpectedEventQuantity = 0,
                    RatesByType = new Dictionary<int, RateInfo>()
                };
            }
            catch (Exception createEx)
            {
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateIbs: create failed for product {0} season {1}: {2}",
                    productId, seasonId, createEx.Message);
                return null;
            }
        }

        // --- Rate auto-creation --------------------------------------------

        private static RateInfo TryAutoCreateRate(
            IOrganizationService service,
            Guid ibsId,
            int rateType,
            ProductRequest req,
            ITracingService tracingService)
        {
            var newRate = new Entity("ats_rate");
            newRate["ats_inventorybyseason"] = new EntityReference("ats_inventorybyseason", ibsId);
            newRate["ats_ratetype"] = new OptionSetValue(rateType);
            newRate["ats_price"] = new Money(req.Rate > 0 ? req.Rate : 0m);
            if (req.HardCost > 0m) newRate["ats_hardcost"] = new Money(req.HardCost);
            if (req.ProductionCost > 0m) newRate["ats_productioncost"] = new Money(req.ProductionCost);
            newRate["ats_autogenerated"] = true;

            try
            {
                var newRateId = service.Create(newRate);
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateRate: created rate {0} for ibs {1} rateType {2}",
                    newRateId, ibsId, rateType);
                return new RateInfo { RateId = newRateId, Inactive = false };
            }
            catch (Exception createEx)
            {
                TraceHelper.Trace(tracingService,
                    "TryAutoCreateRate: create failed for ibs {0} rateType {1}: {2}",
                    ibsId, rateType, createEx.Message);
                return null;
            }
        }

        // --- Verdict evaluator ---------------------------------------------

        private static PairVerdict EvaluatePair(RequestedPair pair, BulkResolution resolution)
        {
            var verdict = new PairVerdict
            {
                productId = pair.ProductId.ToString(),
                seasonId = pair.SeasonId == Guid.Empty ? null : pair.SeasonId.ToString(),
                ibsAutoCreated = pair.IbsAutoCreated,
                rateAutoCreated = pair.RateAutoCreated
            };

            if (pair.SeasonId == Guid.Empty)
            {
                verdict.verdict = "ibs_missing";
                return verdict;
            }

            var key = MakePairKey(pair.ProductId, pair.SeasonId);
            if (!resolution.Ibs.TryGetValue(key, out var info))
            {
                verdict.ibsExists = false;
                verdict.verdict = "ibs_missing";
                return verdict;
            }

            verdict.ibsExists = true;
            verdict.ibsId = info.IbsId.ToString();
            verdict.qtyAvailable = info.QuantityAvailable;
            verdict.allowOverselling = info.AllowOverselling;
            verdict.unlimitedQuantity = info.UnlimitedQuantity;

            int rateType = NormalizeRateType(pair.Req.RateType);
            if (!info.RatesByType.TryGetValue(rateType, out var rateInfo) || rateInfo.Inactive)
            {
                verdict.rateExists = false;
                verdict.verdict = "rate_missing";
                return verdict;
            }
            verdict.rateExists = true;
            verdict.rateId = rateInfo.RateId.ToString();

            if (!info.UnlimitedQuantity && !info.AllowOverselling)
            {
                int lineQty = rateType == RateTypeSeason
                    ? pair.Req.QtyUnits * Math.Max(1, info.ExpectedEventQuantity)
                    : pair.Req.QtyUnits * pair.Req.QtyEvents;

                if (lineQty > info.QuantityAvailable)
                {
                    verdict.verdict = "oversell_blocked";
                    return verdict;
                }
            }

            verdict.verdict = "ok";
            return verdict;
        }

        // --- Utilities ------------------------------------------------------

        private static string MakePairKey(Guid productId, Guid seasonId)
            => productId.ToString("N") + "|" + seasonId.ToString("N");

        private static HashSet<Guid> ParseSeasonIds(string csv)
        {
            var set = new HashSet<Guid>();
            if (string.IsNullOrWhiteSpace(csv)) return set;
            foreach (var part in csv.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
                if (Guid.TryParse(part.Trim(), out var g)) set.Add(g);
            return set;
        }

        private static int NormalizeRateType(string t)
            => string.Equals(t, "Season", StringComparison.OrdinalIgnoreCase) ? RateTypeSeason : RateTypeIndividual;

        private static void AppendInFilter(StringBuilder sb, string attr, HashSet<Guid> values)
        {
            sb.Append("<condition attribute='").Append(attr).Append("' operator='in'>");
            foreach (var v in values) sb.Append("<value>").Append(v.ToString()).Append("</value>");
            sb.Append("</condition>");
        }

        private static void CopyIfPresent(Entity source, Entity target, string attr)
        {
            if (source.Attributes.ContainsKey(attr)) target[attr] = source[attr];
        }

        private static string GetInputString(IPluginExecutionContext ctx, string name)
        {
            if (ctx.InputParameters.Contains(name) && ctx.InputParameters[name] != null)
                return ctx.InputParameters[name].ToString();
            return null;
        }

        private static void SetResponse(IPluginExecutionContext ctx, AvailabilityResult result)
        {
            ctx.OutputParameters["response"] = JsonSerializer.Serialize(result);
        }

        // --- DTOs ----------------------------------------------------------

        private class ProductRequest
        {
            public string ProductId { get; set; }
            public string RateType { get; set; }
            public decimal Rate { get; set; }
            public decimal HardCost { get; set; }
            public decimal ProductionCost { get; set; }
            public int QtyUnits { get; set; }
            public int QtyEvents { get; set; }
            public string seasonIds { get; set; }
            public string packageLineId { get; set; }
            public bool IsPackage { get; set; }
        }

        private class RequestedPair
        {
            public Guid ProductId;
            public Guid SeasonId;
            public ProductRequest Req;
            public bool IbsAutoCreated;
            public bool RateAutoCreated;
        }

        private class BulkResolution
        {
            public Dictionary<string, IbsInfo> Ibs { get; } = new Dictionary<string, IbsInfo>(StringComparer.OrdinalIgnoreCase);
        }

        private class IbsInfo
        {
            public Guid IbsId;
            public int QuantityAvailable;
            public bool AllowOverselling;
            public bool UnlimitedQuantity;
            public int ExpectedEventQuantity;
            public Dictionary<int, RateInfo> RatesByType;
        }

        private class RateInfo
        {
            public Guid RateId;
            public bool Inactive;
        }

        private class AvailabilityResult
        {
            public bool allOk { get; set; }
            public string generatedAt { get; set; }
            public List<PairVerdict> results { get; set; }
        }

        private class PairVerdict
        {
            public string productId { get; set; }
            public string seasonId { get; set; }
            public string verdict { get; set; } // ok | ibs_missing | rate_missing | oversell_blocked
            public bool ibsExists { get; set; }
            public bool rateExists { get; set; }
            public int qtyAvailable { get; set; }
            public bool allowOverselling { get; set; }
            public bool unlimitedQuantity { get; set; }
            public string ibsId { get; set; }
            public string rateId { get; set; }
            public bool ibsAutoCreated { get; set; }
            public bool rateAutoCreated { get; set; }
        }
    }
}
